knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"' # Wrap the path in quotes
        options:
            encoding: 'utf-8'
    image:
        enabled: false